apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T06:02:44Z"
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "412878"
  uid: a35e5e12-e3f2-4f6f-aaa6-620cdd16d9d0
spec:
  clusterIP: 10.233.35.142
  clusterIPs:
  - 10.233.35.142
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30513
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
